app/models.py
from . import db


class TempSensor(db.Model):
    __tablename__ = 'temp_sensors'
    id = db.Column(db.Integer, primary_key=True)
    serial = db.Column(db.String(64), unique=True)
    sensor_model = db.Column(db.String(64), unique=False)
    sensor_name = db.Column(db.String(64), unique=True)
    sensor_location = db.Column(db.String(64), unique=False)
    scan_frequency = db.Column(db.Integer, unique=False)
    sensor_data = db.relationship('SensorData', backref='TempSensor', lazy='dynamic')

    def __init__(self, sensor_name):
        self.sensor_name = sensor_name

    def __repr__(self):
        return '<Temp Sensor %r>' % self.sensor_name


class SensorData(db.Model):
    __tablename__= 'sensor_data'
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime)
    temp_sensor_id = db.Column(db.Integer, db.ForeignKey('temp_sensors.id'))
    # TODO: rename to temp_value
    value = db.Column(db.Float)

    def to_json(self):
        json_sensor_data = {
            'timestamp': self.timestamp,
            'value': self.value
        }
        return json_sensor_data

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SensorCreate(Form):
    sensor_name = StringField('What is the name of the sensor?', validators=[DataRequired()])
    serial = StringField('What is the serial number of this sensor?', validators=[DataRequired()])


class RecordDatabase(Form):
    button = SubmitField('Record DB Temp Entry')

app/sensors/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SensorCreate(Form):
    sensor_name = StringField('What is the name of the sensor?', validators=[DataRequired()])
    serial = StringField('What is the serial number of this sensor?', validators=[DataRequired()])
    submit = SubmitField('Save Me!')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config, Config
from flask_moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from celery import Celery

bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
celery = Celery(__name__, broker=Config.CELERY_BROKER_URL)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    celery.conf.update(app.config)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .sensors import sensors as sensors_blueprint
    app.register_blueprint(sensors_blueprint)
    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')

    return app

app/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import temp

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, url_for, current_app, session, redirect
from .. import db
from ..models import TempSensor, SensorData
from . import main
from .forms import SensorCreate


@main.route('/', methods=['GET', 'POST'])
def index():
    sensors = TempSensor.query.all()
    sensor_data = SensorData.query.all()
    return render_template('index.html', sensors=sensors, sensor_data=sensor_data)

app/sensors/__init__.py
from flask import Blueprint

sensors = Blueprint('sensors', __name__)

from . import views

app/sensors/views.py
from flask import render_template, url_for, flash
from .. import db
from . import sensors
from ..models import TempSensor
from .forms import SensorCreate


@sensors.route('/sensors', methods=['GET', 'POST'])
def addsensor():
    form = SensorCreate()
    return render_template('sensors/addsensor.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask of Beer{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'img/favicon.ico') }}"
      type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'img/favicon.ico') }}"
      type="image/x-icon">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}">
<script src="{{ url_for('static', filename = 'js/raphael.2.1.0.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'js/justgage.1.0.1.min.js') }}"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask Of Beer</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('sensors.addsensor') }}">Sensors</a> </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Flask of Beer{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="one-third column">
            <h1>Welcome!</h1>
            <p>The current temperature is:</p>
            </br>
            <div id="gauge" style="width:400px; height:320px"></div>
            <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js"></script>
<script src="{{ url_for('static', filename = 'js/temp.js') }}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script>
var $temp = "";
function GetTemp(){
        $.ajax({
        url: "api/v1.0/temp/{{ sensors[0].serial }}",
        data: {
            format: 'json'
        },
        async: false,
        type: "GET",
        success: function(data) {
            $temp = data.temp_f;
        }
    });
};
GetTemp();

setInterval(function() {
    GetTemp();
    g5.refresh($temp);
}, 5000);

    var g5 = new JustGage({
    id: "gauge",
    value: $temp,
    min: 50,
    max: 100,
    title: "{{ sensors[0].sensor_name }}",
    label: "",
    levelColorsGradient: false,
    valueFontColor: "gray",
    refreshAnimationTime: 15,
    showInnerShadow: true,
    shadowSize: 4
  });
</script>
<script>
var results = "";

function GetTemps() {
    $.ajax({
        url: "api/v1.0/temp/250",
        data: {
            format: 'json'
        },
        async: false,
        type: "GET",
        success: function(data) {
            results = data.results;
        }
    });
};
// TODO: Convert chart to read direct from JSON data instead of wacky conversion below.
GetTemps();
var times = [];
var temps = [];
var len = results.length;

for(var i = 0; i < len; i++) {
    times.push(results[i].timestamp);
    temps.push(results[i].value);
}

$(function () {
    $('#container').highcharts({
        chart: {
            zoomType: 'x'
        },
        title: {
            text: 'Temps',
            x: -20 //centered
        },
        subtitle: {
            text: 'Source: Raspberry Pi',
            x: -20
        },
        xAxis: {
            categories: times,
            type: 'datetime'
        },
        yAxis: {
            title: {
                text: 'Temperature (F)'
            }
        },
        tooltip: {
            valueSuffix: 'F'
        },
        legend: {
            enabled: false
        },

        plotOptions: {
                area: {
                    fillColor: {
                        linearGradient: {
                            x1: 0,
                            y1: 0,
                            x2: 0,
                            y2: 1
                        },
                        stops: [
                            [0, Highcharts.getOptions().colors[0]],
                            [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                        ]
                    },
                    marker: {
                        radius: 2
                    },
                    lineWidth: 1,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    },
                    threshold: null
                }
            },
        series: [{
            name: 'Raspi',
            data: temps,
            type: 'area'
        }]
    });
});

/**
 * Dark theme for Highcharts JS
 * @author Torstein Honsi
 */

// Load the fonts
Highcharts.createElement('link', {
   href: '//fonts.googleapis.com/css?family=Unica+One',
   rel: 'stylesheet',
   type: 'text/css'
}, null, document.getElementsByTagName('head')[0]);

Highcharts.theme = {
   colors: ["#2b908f", "#90ee7e", "#f45b5b", "#7798BF", "#aaeeee", "#ff0066", "#eeaaee",
      "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
   chart: {
      backgroundColor: {
         linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 },
         stops: [
            [0, '#2a2a2b'],
            [1, '#3e3e40']
         ]
      },
      style: {
         fontFamily: "'Unica One', sans-serif"
      },
      plotBorderColor: '#606063'
   },
   title: {
      style: {
         color: '#E0E0E3',
         textTransform: 'uppercase',
         fontSize: '20px'
      }
   },
   subtitle: {
      style: {
         color: '#E0E0E3',
         textTransform: 'uppercase'
      }
   },
   xAxis: {
      gridLineColor: '#707073',
      labels: {
         style: {
            color: '#E0E0E3'
         }
      },
      lineColor: '#707073',
      minorGridLineColor: '#505053',
      tickColor: '#707073',
      title: {
         style: {
            color: '#A0A0A3'

         }
      }
   },
   yAxis: {
      gridLineColor: '#707073',
      labels: {
         style: {
            color: '#E0E0E3'
         }
      },
      lineColor: '#707073',
      minorGridLineColor: '#505053',
      tickColor: '#707073',
      tickWidth: 1,
      title: {
         style: {
            color: '#A0A0A3'
         }
      }
   },
   tooltip: {
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      style: {
         color: '#F0F0F0'
      }
   },
   plotOptions: {
      series: {
         dataLabels: {
            color: '#B0B0B3'
         },
         marker: {
            lineColor: '#333'
         }
      },
      boxplot: {
         fillColor: '#505053'
      },
      candlestick: {
         lineColor: 'white'
      },
      errorbar: {
         color: 'white'
      }
   },
   legend: {
      itemStyle: {
         color: '#E0E0E3'
      },
      itemHoverStyle: {
         color: '#FFF'
      },
      itemHiddenStyle: {
         color: '#606063'
      }
   },
   credits: {
      style: {
         color: '#666'
      }
   },
   labels: {
      style: {
         color: '#707073'
      }
   },

   drilldown: {
      activeAxisLabelStyle: {
         color: '#F0F0F3'
      },
      activeDataLabelStyle: {
         color: '#F0F0F3'
      }
   },

   navigation: {
      buttonOptions: {
         symbolStroke: '#DDDDDD',
         theme: {
            fill: '#505053'
         }
      }
   },

   // scroll charts
   rangeSelector: {
      buttonTheme: {
         fill: '#505053',
         stroke: '#000000',
         style: {
            color: '#CCC'
         },
         states: {
            hover: {
               fill: '#707073',
               stroke: '#000000',
               style: {
                  color: 'white'
               }
            },
            select: {
               fill: '#000003',
               stroke: '#000000',
               style: {
                  color: 'white'
               }
            }
         }
      },
      inputBoxBorderColor: '#505053',
      inputStyle: {
         backgroundColor: '#333',
         color: 'silver'
      },
      labelStyle: {
         color: 'silver'
      }
   },

   navigator: {
      handles: {
         backgroundColor: '#666',
         borderColor: '#AAA'
      },
      outlineColor: '#CCC',
      maskFill: 'rgba(255,255,255,0.1)',
      series: {
         color: '#7798BF',
         lineColor: '#A6C7ED'
      },
      xAxis: {
         gridLineColor: '#505053'
      }
   },

   scrollbar: {
      barBackgroundColor: '#808083',
      barBorderColor: '#808083',
      buttonArrowColor: '#CCC',
      buttonBackgroundColor: '#606063',
      buttonBorderColor: '#606063',
      rifleColor: '#FFF',
      trackBackgroundColor: '#404043',
      trackBorderColor: '#404043'
   },

   // special colors for some of the
   legendBackgroundColor: 'rgba(0, 0, 0, 0.5)',
   background2: '#505053',
   dataLabelsColor: '#B0B0B3',
   textColor: '#C0C0C0',
   contrastTextColor: '#F0F0F3',
   maskColor: 'rgba(255,255,255,0.3)'
};

// Apply the theme
Highcharts.setOptions(Highcharts.theme);
</script>
{% endblock %}

app/templates/sensors/addsensor.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flask of Beer - Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Add Sensor</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}